meta_product_name: "CIV Alumni"
meta_title: "CIV Alumni - Le lien entre les promos du CIV"
meta_description: "Enfin une appli pour connecter les actuels étudiants en prépa et les alumni du CIV et pour éclairer les nouvelles générations de prépa."
meta_image: "PrepaCIV.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
