meta_product_name: "CIV Alumni"
meta_title: "CIV Alumni - L'appli entre les promos"
meta_description: "Appli pour connecter les étudiants et alumni du CIV"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
